Update .github/workflows/go-tests.yml
Co-authored-by: Sam Salisbury <samsalisbury@gmail.com>

diff --git a/.github/workflows/go-tests.yml b/.github/workflows/go-tests.yml
--- a/.github/workflows/go-tests.yml
+++ b/.github/workflows/go-tests.yml
@@ -52,10 +52,14 @@ jobs:
       # Install gotestsum with go get for 1.15.3; otherwise default to go install 
       - name: Install gotestsum
         run: |
-          if [ ${{ matrix.go-version }} == 1.15.3 ]; then
-              go get gotest.tools/gotestsum@v1.8.2; else
-              go install gotest.tools/gotestsum@v1.8.2
-          fi  
+          GTS="gotest.tools/gotestsum@v1.8.2"
+          # We use the same error message prefix in either failure case, so just define it once here.
+          ERROR="Failed to install $GTS"
+          # First try to 'go install', if that fails try 'go get'...
+          go install "$GTS" || go get "$GTS" || { echo "$ERROR: both 'go install' and 'go get' failed"; exit 1; }
+          # Check that the gotestsum command was actually installed in the path...
+          command -v gotestsum > /dev/null 2>&1 || { echo "$ERROR: gotestsum command not installed"; exit 1; }
+          echo "OK: Command 'gotestsum' installed ($GTS)"
       
       - name: Run go tests
         run: |
